server:
  port: 8080
spring:
  datasource:
    username: root
    password: zzl6451717
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
   view:
     prefix: /templates/
     suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.zout.vip.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
